"""Simulator status service for read-only query of independent daemon heartbeat.

Contracts & Constraints (KI-039):
1. Reads output/simulator_status.json generated by mod-simulator.service.
2. Does NOT import simulation package or business_simulator.
3. Does NOT connect to DB, create engines, or execute subprocesses.
4. Whitelist filtering on response fields to prevent secret/path leakage.
5. Handles states:
   - Fresh (status in file, fresh=True)
   - Stale (timestamp > threshold, status="STALE", fresh=False)
   - Missing (status="UNAVAILABLE", fresh=False)
   - Corrupted/Malformed (status="UNAVAILABLE", fresh=False, no 500)
   - PermissionError (raises PermissionError -> caught by API as 503)
"""

from __future__ import annotations

from datetime import datetime, timezone
import json
import logging
import os
from pathlib import Path
import time
from typing import Any, Dict, Optional
from zoneinfo import ZoneInfo

logger = logging.getLogger(__name__)

HK_TZ = ZoneInfo("Asia/Hong_Kong")
DEFAULT_STALE_SECONDS = 180.0


def get_default_status_path() -> Path:
    """Resolve the default status file path without hardcoding machine-specific paths."""
    env_path = os.getenv("MOD_SIMULATOR_STATUS_PATH")
    if env_path:
        return Path(env_path).resolve()

    # Discover project root by navigating up from current file
    current_file = Path(__file__).resolve()
    # In dev repo: <repo>/backend/app/services/simulator_status.py -> parents[3] is <repo>
    # In release: <repo>/backend/releases/<ts>/services/simulator_status.py -> parents[4] is <repo>
    for parent in current_file.parents:
        candidate = parent / "output" / "simulator_status.json"
        if candidate.exists():
            return candidate

    for parent in current_file.parents:
        candidate = parent / "output" / "simulator_status.json"
        if (parent / "output").is_dir():
            return candidate

    # Fallback to current working directory / output
    return Path("output/simulator_status.json").resolve()


def get_stale_threshold_seconds() -> float:
    """Return the threshold in seconds after which a heartbeat is considered STALE."""
    try:
        raw = os.getenv("MOD_SIMULATOR_STALE_SECONDS")
        if raw is not None:
            return max(5.0, float(raw))
    except (ValueError, TypeError):
        pass
    return DEFAULT_STALE_SECONDS


def _parse_timestamp(raw_ts: Any) -> Optional[datetime]:
    """Safely parse an ISO 8601 timestamp string into a timezone-aware datetime."""
    if not isinstance(raw_ts, str) or not raw_ts.strip():
        return None
    try:
        dt = datetime.fromisoformat(raw_ts.strip())
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=HK_TZ)
        return dt
    except Exception:
        return None


def _sanitize_fuse_metrics(raw: Any) -> Optional[Dict[str, int]]:
    """Ensure fuse metrics only contain expected integer fields."""
    if not isinstance(raw, dict):
        return None
    result = {}
    for key in ("minute_count", "max_per_minute", "day_count", "max_per_day"):
        val = raw.get(key)
        if isinstance(val, (int, float)):
            result[key] = int(val)
    return result if result else None


def read_simulator_status(
    status_path: Optional[Path] = None,
    now: Optional[datetime] = None,
    stale_threshold: Optional[float] = None,
) -> Dict[str, Any]:
    """Read and sanitize the simulator heartbeat status.

    Returns a fixed dictionary contract:
    {
        "service": str,
        "status": str ("RUNNING", "DEGRADED", "HALTED", "STALE", "UNAVAILABLE"),
        "last_cycle_status": Optional[str],
        "timestamp": Optional[str],
        "fresh": bool,
        "fail_closed_tripped": bool,
        "fuse_metrics": Optional[Dict[str, int]],
        "uptime_seconds": Optional[float],
        "consecutive_failures": int,
        "notice": Optional[str],
        "enabled": bool,
    }
    """
    path = status_path if status_path is not None else get_default_status_path()
    threshold = stale_threshold if stale_threshold is not None else get_stale_threshold_seconds()

    base_response: Dict[str, Any] = {
        "service": "mod-simulator",
        "status": "UNAVAILABLE",
        "last_cycle_status": None,
        "timestamp": None,
        "fresh": False,
        "fail_closed_tripped": False,
        "fuse_metrics": None,
        "uptime_seconds": None,
        "consecutive_failures": 0,
        "notice": None,
        "enabled": False,
    }

    if not path.exists():
        base_response["notice"] = "Simulator heartbeat file not found"
        return base_response

    # Read with finite retry (to handle any atomic file rename window)
    raw_text = None
    read_error = None
    for _ in range(3):
        try:
            with open(path, "r", encoding="utf-8") as f:
                raw_text = f.read()
            break
        except PermissionError:
            # Fatal permission issue - caller should return 503
            raise
        except (OSError, IOError) as ex:
            read_error = ex
            time.sleep(0.02)

    if raw_text is None:
        logger.warning(f"Could not read simulator status after retries: {read_error}")
        base_response["notice"] = "Simulator heartbeat file unreadable"
        return base_response

    if not raw_text.strip():
        base_response["notice"] = "Simulator heartbeat file is empty"
        return base_response

    try:
        data = json.loads(raw_text)
    except Exception:
        base_response["notice"] = "Simulator heartbeat file contains malformed JSON"
        return base_response

    if not isinstance(data, dict):
        base_response["notice"] = "Simulator heartbeat file content is not a JSON object"
        return base_response

    # Parse and validate timestamp
    raw_ts = data.get("timestamp")
    parsed_dt = _parse_timestamp(raw_ts)

    current_now = now if now is not None else datetime.now(timezone.utc)
    if current_now.tzinfo is None:
        current_now = current_now.replace(tzinfo=timezone.utc)

    fresh = False
    status = str(data.get("status", "UNAVAILABLE"))
    notice = None

    if parsed_dt is None:
        fresh = False
        status = "UNAVAILABLE"
        notice = "Invalid or missing timestamp in heartbeat"
    else:
        # Convert both to UTC for reliable age comparison
        dt_utc = parsed_dt.astimezone(timezone.utc)
        now_utc = current_now.astimezone(timezone.utc)
        age_seconds = (now_utc - dt_utc).total_seconds()

        if age_seconds < -30.0:
            # Future timestamp (clock skew > 30s)
            fresh = False
            status = "UNAVAILABLE"
            notice = f"Heartbeat timestamp is in the future (skew: {abs(age_seconds):.1f}s)"
        elif age_seconds > threshold:
            # Heartbeat expired
            fresh = False
            status = "STALE"
            notice = f"Heartbeat expired (age: {age_seconds:.1f}s > {threshold:.1f}s threshold)"
        else:
            fresh = True
            # Status from file if valid enum, else fallback to RUNNING
            if status not in ("RUNNING", "DEGRADED", "HALTED"):
                status = "RUNNING"

    # Whitelist fields mapping
    last_cycle_status = data.get("last_cycle_status")
    if last_cycle_status is not None:
        last_cycle_status = str(last_cycle_status)[:50]

    fail_closed_tripped = bool(data.get("fail_closed_tripped", False))

    uptime_raw = data.get("uptime_seconds")
    uptime = None
    if isinstance(uptime_raw, (int, float)) and uptime_raw >= 0:
        uptime = float(uptime_raw)

    failures_raw = data.get("consecutive_failures", 0)
    consecutive_failures = int(failures_raw) if isinstance(failures_raw, (int, float)) else 0

    fuse_metrics = _sanitize_fuse_metrics(data.get("fuse_metrics"))

    return {
        "service": "mod-simulator",
        "status": status,
        "last_cycle_status": last_cycle_status,
        "timestamp": str(raw_ts) if raw_ts is not None else None,
        "fresh": fresh,
        "fail_closed_tripped": fail_closed_tripped,
        "fuse_metrics": fuse_metrics,
        "uptime_seconds": uptime,
        "consecutive_failures": consecutive_failures,
        "notice": notice,
        "enabled": fresh and (status in ("RUNNING", "DEGRADED")),
    }
