#!/usr/bin/env python3
"""Validate the reproducible git-cliff changelog contract.

Owner: project governance tooling.
Input: cliff.toml, .git-cliff-baseline, CHANGELOG.md, and local Git history.
Output: diagnostics only; this script is read-only.
Risk: none. It never changes files, tags, commits, or external systems.
"""

from __future__ import annotations

import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EXPECTED_VERSION = "2.13.1"
ACTION_SHA = "f50e11560dce63f7c33227798f90b924471a88b5"
GENERATED_MARKER = f"generated by git-cliff {EXPECTED_VERSION}; do not edit manually"


def validate_baseline(value: str) -> list[str]:
    return [] if re.fullmatch(r"[0-9a-f]{40}", value) else ["基线必须是 40 位小写 Git SHA"]


def validate_config(data: dict[str, object]) -> list[str]:
    errors: list[str] = []
    changelog = data.get("changelog")
    git = data.get("git")
    if not isinstance(changelog, dict) or GENERATED_MARKER not in str(
        changelog.get("header", "")
    ):
        errors.append("cliff.toml 缺少锁定版本的生成标记")
    if not isinstance(git, dict) or git.get("conventional_commits") is not True:
        errors.append("cliff.toml 未强制 Conventional Commits")
    if isinstance(changelog, dict) and "v0.1.0" in str(changelog.get("header", "")):
        errors.append("cliff.toml 仍声称存在 v0.1.0 虚假基线标签")
    return errors


def validate_changelog(text: str) -> list[str]:
    errors: list[str] = []
    if not text.startswith("# 变更日志"):
        errors.append("CHANGELOG.md 缺少标准中文标题")
    if GENERATED_MARKER not in text:
        errors.append("CHANGELOG.md 不是由锁定版本 git-cliff 生成")
    if "v0.1.0" in "\n".join(text.splitlines()[:12]):
        errors.append("CHANGELOG.md 头部仍声称虚假 v0.1.0 基线")
    return errors


def validate_workflow(text: str) -> list[str]:
    errors: list[str] = []
    if f"orhun/git-cliff-action@{ACTION_SHA}" not in text:
        errors.append("CHANGELOG workflow 未锁定 git-cliff action 提交")
    if f"version: v{EXPECTED_VERSION}" not in text:
        errors.append("CHANGELOG workflow 未锁定 git-cliff 版本")
    if "contents: read" not in text:
        errors.append("CHANGELOG workflow 未保持只读权限")
    return errors


def git_ok(*args: str) -> bool:
    return (
        subprocess.run(
            ["git", *args], cwd=ROOT, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
        ).returncode
        == 0
    )


def main() -> int:
    errors: list[str] = []
    baseline_path = ROOT / ".git-cliff-baseline"
    config_path = ROOT / "cliff.toml"
    changelog_path = ROOT / "CHANGELOG.md"
    workflow_path = ROOT / ".github" / "workflows" / "changelog.yml"

    baseline = baseline_path.read_text(encoding="utf-8").strip()
    errors.extend(validate_baseline(baseline))
    with config_path.open("rb") as handle:
        errors.extend(validate_config(tomllib.load(handle)))
    errors.extend(validate_changelog(changelog_path.read_text(encoding="utf-8")))
    errors.extend(validate_workflow(workflow_path.read_text(encoding="utf-8")))

    if not errors and not git_ok("cat-file", "-e", f"{baseline}^{{commit}}"):
        errors.append("基线提交不存在")
    if not errors and not git_ok("merge-base", "--is-ancestor", baseline, "HEAD"):
        errors.append("基线提交不是 HEAD 的祖先")

    if errors:
        for error in errors:
            print(f"  CHANGELOG GOVERNANCE  {error}")
        print(f"\n[changelog] {len(errors)} 个问题。", file=sys.stderr)
        return 1

    print(f"[changelog] OK: baseline reachable, git-cliff {EXPECTED_VERSION} contract valid.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
